default:
	cat justfile

setup:
	rm -rf .venv
	venv python setup 3.11

install-requirements:
	uv pip install -r requirements.txt

install-pyproject:
	uv pip install -r pyproject.toml

serve:
	streamlit run Home.py

run: serve
