[pytest]
pythonpath = .

markers =
    integration: tests that call a real Ollama server
    with_model_installed: tests that require a specific model to be installed
    with_model_uninstalled: tests that require a specific model to be uninstalled

log_cli = true
log_cli_level = INFO
